### ISSUE TITLE
Part of cross-section not loaded [sectionproperties implementation]

### ISSUE THREAD

**Issue by robbievanleeuwen** [normanrichardson/rhino_shapely_interop#7]
Loading a surface from a rhino file into *sectionproperties* resulted in not all of the cross-section being loaded.

Code snippet:

```python
from sectionproperties.pre.geometry import Geometry, CompoundGeometry
from sectionproperties.analysis.section import Section

geom = Geometry.from_3dm(filepath="DIES01_POLYLINES.3dm")
geom.plot_geometry()
```

Below is a screenshot from Rhino (expected behaviour):
![die](https://user-images.githubusercontent.com/18841910/153125657-af244e08-f915-47f7-8e92-07fb08835a12.png)

Below is the geometry object I get from the above code:
![Figure_1](https://user-images.githubusercontent.com/18841910/153125731-46869973-2849-4005-846d-6c3c2a5f58f5.png)

I get a deprecation warning in the terminal when executing the above code, so not sure if that is relevant to this issue at all:

```shell
\rhino_shapely_interop\importers.py:410: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  [LinearRing(line) for line in line_list]
```

Attached is the offending Rhino file.

[DIES01_POLYLINES.zip](https://github.com/normanrichardson/rhino_shapely_interop/files/8029558/DIES01_POLYLINES.zip)

**Comment by normanrichardson** [comment]
@robbievanleeuwen thanks for this. The issue seems to be coming from [here](https://github.com/normanrichardson/rhino_shapely_interop/blob/0e29f60db77bf29273a1178686dbb72a36ceffaf/rhino_shapely_interop/importers.py#L398-L413). The endpoints of the Brep edges are out (by some precision), so linemerge is not returning a list of LinearRing, but rather a list of LinearRing and a bunch of LineString. I'm working on a fix.

**Comment by normanrichardson** [comment]
@robbievanleeuwen this should be fixed in master. Let me know if this works for you and I'll create a new release.

**Comment by robbievanleeuwen** [comment]
@normanrichardson master branch works for me :)

**Comment by normanrichardson** [comment]
@robbievanleeuwen great, the updated release is complete.
